version: '3'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    environment:
      PORT: 3000 
    networks:
      - app-net

networks:
  app-net:
    driver: bridge